### PR TITLE
fix(filmstrip): keep AudioTracksContainer in the DOM while Filmstrip is hidden in reduced UI

### LINKED ISSUE #16883: Shrinking window with chat open cuts off audio of other participants
### Description of the issue:

I was in a chat with someone earlier today, who suddenly stopped being able to hear me.  I wasn't muted... we did a little debugging, and it turned out that when he shrunk his window, he couldn't hear me.  We tinkered with it a bit, and found a reproducible test case (where I could observe the behavior, even on a different OS), which follows.

### Reproduction steps:

1. initiate a jitsi call in in-browser (I'm using Chromium Jitsi client
2. open the Chat sub-window in your call
3. shrink your window (at the OS/window-manager level) enough that the chat hides itself

### Expected behavior:

Still being able to hear the other person/people on the call.

### Actual behavior:

Once the window gets small enough, the chat section disappears (which is fine), but also I stop being able to hear the other person.

Attached screenshots are of me reproducing this locally on my own computer with two windows (one in Incognito) connected to the same chat.  The non-incognito (small) window is muted, but the incognito (larger) window never is. 

1st screenshot shows that when I talk, the audio is coming through (dots on incognito, and ring around the green circle in the small window):

Image

2nd screenshot shows what happens when I shrink that window (by just a few pixels -- note the slight gap between the window edge and the incognito indicator of the other window, which were overlapping in the first screenshot -- nothing else should have moved) that when I'm talking, and can see the dots in the incognito window, the ring isn't present around the green circle, and I'm correspondingly no longer able to hear the other person (myself, in this test case):

Image

### Platform

- [x] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

143.0.7499.146

### Relevant log output

```shell

```

### Reproducibility

- [x] The problem is reproducible on meet.jit.si

### More details?

More detailed browser version info from chrome://version :

Chromium	143.0.7499.146 (Official Build) snap (64-bit)
Revision	c1224fc40c96e7f17f0cdeb87a8f4c64b93c0d74-refs/branch-heads/7499@{#3315}
OS	Linux
JavaScript	V8 14.3.127.17

Don't know how to determine the jitsi meet version, but it's whatever is live on meet.jit.si as of the time of this report.

### PR DESCRIPTION
**Pull request by Calinteodor**
Fix #16883 
Related #16854

### CODE REVIEW

File: react/features/conference/components/web/Conference.tsx [hunk 1]
```diff
@@ -257,14 +257,21 @@ class Conference extends AbstractConference<IProps, any> {
...
+                            </>
                         </div>
-                        <span
-                            aria-level = { 1 }
-                            className = 'sr-only'
-                            role = 'heading'>
-                            { t('toolbar.accessibilityLabel.heading') }
-                        </span>
-                        <Toolbox />
+                        <>
```
Comment (hristoterezov) [inline react/features/conference/components/web/Conference.tsx]: Why do we need <>?

File: react/features/conference/components/web/Conference.tsx [hunk 2]
```diff
@@ -257,14 +257,21 @@ class Conference extends AbstractConference<IProps, any> {
                             id = 'videospace'
                             onTouchStart = { this._onVideospaceTouchStart }>
                             <LargeVideo />
+                            <>
```
Comment (hristoterezov) [inline react/features/conference/components/web/Conference.tsx]: Why do we need the change?

Comment (Calinteodor) [reply react/features/conference/components/web/Conference.tsx]: Thought it would look better structured, but we can remove it.

File: react/features/conference/components/web/Conference.tsx (hunk 1 above)
Comment (Calinteodor) [reply react/features/conference/components/web/Conference.tsx]: Ditto.

File: react/features/conference/components/web/Conference.tsx (hunk 2 above)
Comment (hristoterezov) [reply react/features/conference/components/web/Conference.tsx]: But wait weren't those components already added somewhere. Why do we add them again?

Comment (Calinteodor) [reply react/features/conference/components/web/Conference.tsx]: That's if you are talking about grouping them inside fragments, but Filmstrip components need to be there.

Comment (Calinteodor) [reply react/features/conference/components/web/Conference.tsx]: The Filmstrip components need to be there for reduced UI too, because of AudioTracksContainer.

File: react/features/conference/components/web/Conference.tsx (hunk 1 above)
Comment (hristoterezov) [reply react/features/conference/components/web/Conference.tsx]: Could you please remove them
