### PR TITLE
 GSoC: fix(recording): show advanced options for local recording with transcription 

### LINKED ISSUE #16938: Advanced Options missing in Recording Dialog for local recording only setups
### What happened?

In Jitsi Meet installations without Jibri and with recordingService.enabled = false,  Advanced Options section is not visible in the Recording Dialog.

Image

Expected Behavior:
Even when recordingService.enabled = false and Jibri is not present, Advanced Options should be visible in the recording dialog, especially for local recording setups. This allows users to configure local recording, and **enabling backend transcription** appropriately.

https://community.jitsi.org/t/transcriber-leave-when-moderator-leave/139875

### Platform

- [x] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [x] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

jitsi meet 2.0.10741 Google Chrome 143

### Relevant log output

```shell

```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

When recordingService.enabled is manually set to true, the Advanced Options do appear, but this introduces an additional, non-functional recording service option that generates errors when enabled (since Jibri is not present). 

Image

### PR DESCRIPTION
**Pull request by mishraditi**
Fix #16938

## Description 
In setups without Jibri and with recording service disabled, the Advanced Options section in the Recording Dialog was not visible at all, even when local recording and a backend transcription service were configured. This meant users had no way                                                                               to enable backend transcription when using local recording.               

This PR fixes the visibility of Advanced Options so it appears when local recording is available, and ensures that the transcription toggle in those options actually takes effect when the user starts a local recording.
 
  ## Testing

  Since local config changes do not take effect in the dev environment, testing was done by temporarily hardcoding values in [AbstractStartRecordingDialogContent](https://github.com/jitsi/jitsi-meet/blob/master/react/features/recording/components/Recording/AbstractStartRecordingDialogContent.tsx) that simulate a setup with no Jibri and an available transcription backend.

  ```diff
  -        _canStartTranscribing: canAddTranscriber(state),
  +        _canStartTranscribing: true,
           _hideStorageWarning: Boolean(recordingService?.hideStorageWarning),
  -        _renderRecording: isJwtFeatureEnabled(state, MEET_FEATURES.RECORDING, false),
  +        _renderRecording: false,
  ```

  With these values in place, Advanced Options are visible in the Recording Dialog when local recording is selected.

## Screenshot
screenshot

### CODE REVIEW

**Comment by mishraditi** [comment]
Hi @saghul, @damencho,
I’ve fixed #16938 as suggested and pushed the changes. Could you please review my PR?

**Comment by mishraditi** [comment]
Hi @saghul, @damencho
This is working fine locally. Could you please review and let me know if any changes are required?

**Comment by damencho** [comment]
But what will happen if there is no recording enabled?

**Comment by damencho** [comment]
Are you planning to address that or I can take it as it is next on my plate?

**Comment by mishraditi** [comment]
Yes, I’m planning to address this.

**Comment by mishraditi** [comment]
Hi, I've now worked on the edge case to handle when none of the services are available. In this case, it will now show a warning that neither the recording service nor local recording is enabled, and disable the "Start Recording" button.
 
I am attaching screenshots below for both cases , when no service is available, and when every service is available

## Screenshots
Screenshot 2026-02-25 at 16 07 17


Screenshot 2026-02-25 at 16 09 32

File: react/features/recording/components/Recording/AbstractStartRecordingDialog.ts [hunk 1]
```diff
@@ -173,18 +173,21 @@ class AbstractStartRecordingDialog extends Component<IProps, IState> {
...
             selectedRecordingService = RECORDING_TYPES.JITSI_REC_SERVICE;
         } else if (this._areIntegrationsEnabled()) {
             if (props._localRecordingEnabled && supportsLocalRecording()) {
                 selectedRecordingService = RECORDING_TYPES.LOCAL;
             } else {
                 selectedRecordingService = RECORDING_TYPES.DROPBOX;
             }
+        } else if (props._localRecordingEnabled && supportsLocalRecording()) {
+            selectedRecordingService = RECORDING_TYPES.LOCAL;
         }
```
Comment (mishraditi) [inline react/features/recording/components/Recording/AbstractStartRecordingDialog.ts:189]: The `|| !this._areIntegrationsEnabled()` part meant: If Dropbox is not configured, still default to the cloud recording service, this caused a bug, in setups where Jibri is not present and Dropbox is not configured (e.g., local-recording-only setups, or setups with no recording service at all), the dialog would incorrectly pre-select `JITSI_REC_SERVICE`, making the "Start Recording" button clickable even though cloud recording was unavailable.

**Comment by damencho** [comment]
Well there are cases where recording is not available for you and just transcription, so that message is not a good option. 

The most obvious case is that I have a token where just transcription is allowed to me and I should be able to enable just the transcription from that dialog.

**Comment by mishraditi** [comment]
## Changes in this update:                                                                                                                                                                                                                                                                                                                                              
 * No recording service but transcription is available -> Only the "Record transcription" toggle is shown directly, without the "Advanced Options" wrapper or the "Record audio and video" toggle.

I have attached the screenshots

## Screenshots
<img width="1290" height="860" alt="Screenshot 2026-02-25 at 17 48 07" src="https://github.com/user-attachments/assets/bf35925b-78a9-4fa4-8781-915a8ed45683" />

<img width="1290" height="860" alt="Screenshot 2026-02-25 at 17 48 00" src="https://github.com/user-attachments/assets/8b34cc23-cd6a-49eb-a7b7-e026aeb60a2b" />

**Comment by damencho** [comment]
> * No recording service and no transcription available -> A warning message is displayed and the "Start Recording" button is disabled.

Can you drop this, and the message itself. You should not have a button to come to the dialog when this is the case. So if you manage to open an empty dialog that is a bug that needs to be addressed somewhere else. 
Thank you

**Comment by mishraditi** [comment]
Done

**Comment by damencho** [comment]
Thank you, shortly I will be testing it.

**Comment by damencho** [comment]
Ignore the lint error, seems the npm registry problem ... will restart it later.

**Comment by damencho** [comment]
I rebased it to latest and foced push because of that.

**Comment by damencho** [comment]
I also add few small changes to make it work with latest master when having only transcription feature in jwt.

**Comment by damencho** [comment]
jenkins test this please

**Comment by damencho** [comment]
Thank you for your contribution
