### PR TITLE
 GSoC: fix(settings): don't activate all mics when audio levels are disabled

### LINKED ISSUE #16964: Mic picker engages all mics despite disableAudioLevels=true
### What happened?

The issue is that the dialogue for choosing a mic seems to "listen" on all mics, not just current one. This makes sense, since it needs to display current audio level for each. However, if I set disableAudioLevels=true (self-hosted instance), the audio levels are no longer displayed, but every mic is still being used. This is annoying as using mic on bluetooth headphones moves them into HFP state and downgrades the audio quality. This state is only reset on page reload.
The following snippet demonstrates (on chromium) that it is possible to list all mics without actually "listening" on them.
```js
async function listMicrophones() {
  await navigator.mediaDevices.getUserMedia({ audio: true });

  const devices = await navigator.mediaDevices.enumerateDevices();

  const microphones = devices.filter(
    device => device.kind === "audioinput"
  );

  microphones.forEach((mic, index) => {
    console.log(`${index + 1}: ${mic.label || "Unnamed microphone"}`);
    console.log(`   deviceId: ${mic.deviceId}`);
    console.log(`   groupId: ${mic.groupId}`);
  });

  return microphones;
}

listMicrophones();
```

### Platform

- [x] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

jitsi/web:stable-10710, chrome 145

### Relevant log output

```shell

```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

_No response_

### PR DESCRIPTION
**Pull request by mishraditi**
fix #16964

# Description : 
Opening the mic picker popup calls `getUserMedia` for every microphone to show audio level meters. When disableAudioLevels=true, the meters are hidden but all mics are still activated. This causes Bluetooth headphones to switch to HFP mode and degrades audio quality.

## Changes:
  - Skip audio track creation in` AudioSettingsContent._setTracks` when measureAudioLevels is false
  - Set` disableAudioLevels: true` in default config
 
##   Testing:
The dev server loads config from the proxy server, so local config.js changes don't take effect. Used `APP.store.dispatch({ type: 'SET_CONFIG', config: { disableAudioLevels: true } })`  in dev console to set the config instead. Verified in chrome://webrtc-internals that no extra getUserMedia calls happen when opening the mic picker , which previously gets called equals to number of mics  when clicking on AudioSettingPopup. If you need I can attach Screenshots.
If the dev server should be loading local config instead, happy to look into that too.

### CODE REVIEW

File: config.js [hunk 1]
```diff
@@ -180,7 +180,7 @@ var config = {
     // Audio
 
     // Disable measuring of audio levels.
-    // disableAudioLevels: false,
```
Comment (damencho) [inline config.js:183]: Don't change this, this indicates the default value of the config.

Comment (mishraditi) [reply config.js:183]: @damencho 
Reverted the config.js change as suggested.

**Comment by damencho** [comment]
Jenkins test this please

**Comment by mishraditi** [comment]
@damencho 
It runs locally, but one CI test is failing. Please let me know why?

**Comment by damencho** [comment]
Hum, we have added retries on that test as it fails randomly without any reason. Your PR is not rebased to latest master and does not have the retry. Can you rebase and force push in your branch?

**Comment by damencho** [comment]
Jenkins test this please

**Comment by damencho** [comment]
@mishraditi have you signed the CLA as I do not see it, thank you?

**Comment by mishraditi** [comment]
Hi @damencho, 
I signed the CLA earlier for a previous PR. Please let me know if I need to sign it again.

**Comment by damencho** [comment]
Sorry, your github username is missing from the CLA and that's why I couldn't find it initially. 
But I see there is a signed CLA for the email you use, which is what matters.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Thank you for your contribution.
