### PR TITLE
Installs required basexx when token package is installed. Fixes #1870.

### LINKED ISSUE #1870: jitsi-meet-tokens missing basexx dependency
Installing the jitsi-meet-tokens debian package leaves the `basexx` luarocks dependency missing.
Using prosody-trunk 1nightly791-1~xenial

`/var/log/prosody/prosody.err`
```
Aug 08 06:35:21 modulemanager   error   Error initializing module 'auth_token' on '192.168.33.11': /usr/bin/prosody:183: module 'basexx' not found:No LuaRocks module found for basexx
        no field package.preload['basexx']
        no file '/usr/lib/prosody/basexx.lua'
        no file '/usr/local/share/lua/5.1/basexx.lua'
        no file '/usr/local/share/lua/5.1/basexx/init.lua'
        no file '/usr/local/lib/lua/5.1/basexx.lua'
        no file '/usr/local/lib/lua/5.1/basexx/init.lua'
        no file '/usr/share/lua/5.1/basexx.lua'
        no file '/usr/share/lua/5.1/basexx/init.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/basexx.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/basexx/init.lua'
        no file '/usr/lib/prosody/basexx.so'
        no file '/usr/local/lib/lua/5.1/basexx.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/basexx.so'
        no file '/usr/lib/lua/5.1/basexx.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/var/lib/prosody/.luarocks/lib/lua/5.1/basexx.so'
stack traceback:
        /usr/lib/prosody/core/modulemanager.lua:31: in function </usr/lib/prosody/core/modulemanager.lua:31>
        [C]: in function '_real_require'
        /usr/bin/prosody:183: in function 'require'
        .../share/jitsi-meet/prosody-plugins/token/util.lib.lua:4: in main chunk
        (tail call): ?
        .../share/jitsi-meet/prosody-plugins/mod_auth_token.lua:8: in main chunk
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/prosody/core/modulemanager.lua:31: in function 'pcall'
        /usr/lib/prosody/core/modulemanager.lua:177: in function 'do_load_module'
        /usr/lib/prosody/core/modulemanager.lua:255: in function 'load'
        /usr/lib/prosody/core/usermanager.lua:66: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/core/hostmanager.lua:104: in function 'activate'
        /usr/lib/prosody/core/hostmanager.lua:57: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/bin/prosody:352: in function 'prepare_to_start'
        /usr/bin/prosody:421: in main chunk
        [C]: ?
```

This can manually be fixed by `# luarocks install basexx`
It should be added to the `jitsi-meet-tokens.postinst` script

### PR DESCRIPTION
**Pull request by damencho**
Adds some debug messages when token verification fails for some reason.

### CODE REVIEW

File: resources/prosody-plugins/mod_auth_token.lua [hunk 1]
```diff
@@ -58,7 +58,12 @@ end
 function provider.get_sasl_handler(session)
 
 	local function get_username_from_token(self, message)
-        local res = token_util:process_and_verify_token(session);
+        local res, error, reason = token_util:process_and_verify_token(session);
+
+        if (res == false) then
+            log("debug",
```
Comment (aaronkvanmeerten) [inline resources/prosody-plugins/mod_auth_token.lua]: Can we make this log level higher than debug?  Maybe info or warning?
