### PR TITLE
fix(polls): add vertical margin to create poll button (android)

### LINKED ISSUE #14536: Create poll button has no vertical margins in android
### Description:

Create poll button has no vertical margins in android

### Steps to reproduce:

1. Join a meet and open polls

### Expected behavior:

Create poll button should have some vertical margin

### Actual behavior:

Create poll button has no vertical margin

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 24.0.1
- Operating System: Android 13

### PR DESCRIPTION
**Pull request by nitinkushwaha17**
fixes #14536

### CODE REVIEW

**Comment by saghul** [comment]
@Calinteodor PTAL

**Comment by nitinkushwaha17** [comment]
@Calinteodor It is a small change. Can you please review this. Thanks.

**Review by Calinteodor — APPROVED** [review]

File: react/features/polls/components/native/styles.ts [hunk 1]
```diff
@@ -208,7 +208,8 @@ export const chatStyles = createStyleSheet({
     },
 
     createPollButtonAndroid: {
-        marginHorizontal: 20
+        marginHorizontal: 20,
+        marginVertical: BaseTheme.spacing[5]
```
Comment (Calinteodor) [inline react/features/polls/components/native/styles.ts:212]: Can you try and see if using our spacing variables is duable?

**Review by Calinteodor — CHANGES_REQUESTED** [review]
